# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a65183df871bae4c768b0c58b16cf0a08b03532fbfae5567e3de1bddc15a15370527e1cb33a114bda3a8afa12d7376a37b31a15d0ebc3d75aef72f3e9c631c1

test:
  secret_key_base: 9e21b1439b704734e62d8d8f134778acdedb68e7359c30c5b3b8432886df03c815f793949f11e74d750be3ecbdbc659e857c42593165d5885047dca9ccb64977

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
